# Generated by Django 4.2.3 on 2023-08-02 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0002_alter_cart_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("cpf", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Credit", "Cartão de crédito"),
                            ("Debit", "Cartão de dédito"),
                            ("Pix", "Pix"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.AddField(
            model_name="sale",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="market.product"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
